### ISSUE TITLE
Parameter Store variable is not created

### ISSUE THREAD

**Issue by herbertgoto** [awslabs/aws-limit-monitor#30]
I ran the solution with 4 accounts and set  up Slack configuration from the Stack. A parameter store for the slack was not created and the lambda fails when sending alerts:

2019-09-27T00:27:36.225Z 0008c69c-9c4f-4758-9f27-aec000e61988 [ERROR]AccessDeniedException: No access to reserved parameter name: awslimitschecker.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

**Comment by herbertgoto** [comment]
I just found the issue. Parameters cannot have prefix aws otherwise they cannot be created. However, Cloudformation stack is completed successfully.

**Comment by gsingh04** [comment]
Thanks for your feedback. I was able to replicate this at my end. We do not fail the deployment due to SSM creation issue, however we log it as error which you can see in cloudwatch logs:

`{`
    `"SSMParameter": {`
        `"channelKey": "awslimitmonitorslackchannel",`
        `"hookKey": "awslimitmonitorslack",`
        `"response": {`
            `"message": "No access to reserved parameter name: awslimitmonitorslackchannel.",`
            `"code": "AccessDeniedException",`
            `"time": "2019-10-11T18:23:56.826Z",`
            `"requestId": "85ef4c07-f248-41bf-aaba-00acfbed43cf",`
            `"statusCode": 400,`
            `"retryable": false,`
            `"retryDelay": 43.4631927186931`
        `}`
    `}`
`}`

We have added this to our backlog items and this will be captured under deployment instructions on solution implementation guide.

**Comment by georgebearden** [comment]
Hi - Closing this issue, but please let us know if you need additional assistance with this.
